const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

prisma.auditoria.deleteMany()
  .then(() => prisma.refreshToken.deleteMany())
  .then(() => prisma.documento.deleteMany())
  .then(() => prisma.comissao.deleteMany())
  .then(() => prisma.kanbanCard.deleteMany())
  .then(() => prisma.contrato.deleteMany())
  .then(() => prisma.venda.deleteMany())
  .then(() => prisma.cliente.deleteMany())
  .then(() => prisma.meta.deleteMany())
  .then(() => prisma.consorcio.deleteMany())
  .then(() => prisma.operacao.deleteMany())
  .then(() => prisma.curso.deleteMany())
  .then(() => prisma.user.deleteMany())
  .then(() => prisma.licenciado.deleteMany())
  .then(() => { console.log('Banco limpo!'); process.exit(0) })
  .catch(e => { console.error('ERRO:', e.message); process.exit(1) })
